### ISSUE TITLE
Triggers

### ISSUE THREAD

**Issue by jeffcshelton** [gt-space/flight#1]
Implement a method of continuous checking of certain sensor values, such that when they cross some threshold, an action is taken. This action should be encoded as a `Sequence`, the same as the ones run after receiving an ordinary sequence from the control server. The most important kind of triggers, abort triggers, should simply be a special case of general triggers where the sequence to be run is simply `abort()`.

This feature will require starting a new thread during the `ProgramState::Init` state, found in `src/state.rs` under the `init()` function. I would likely make a new file for triggers, `triggers.rs`, where you store all of the new code.
- New triggers will be sent to the flight computer by the control server in the `ProgramState::WaitForOperator` state. There is an existing `match` statement in the associated function which differentiates between the variants of `FlightControlMessage` that come from the server. A new branch to this match statement must be added to handle this.
- Store all triggers in `SharedState`, with the other shared state of the flight software. This will make them widely accessible to the program.
- If a check succeeds, then you must run the accompanying sequence in Python. Take a look at the `ProgramState::RunSequence` state for guidance on how to invoke the Python interpreter to run a sequence. It's fairly simple.

Go ahead and attempt the parts of this issue that you reasonably can, but the `servo` and `common` repositories also need to be updated with the new communication protocols to support this before everything will function together. I will try to have those done as soon as possible, and I'll update this issue with a comment once I do.

I have made a branch to house the new feature development and attached it to this issue. **Make sure** you run `git checkout triggers` before making or committing any new changes.

Good luck! Remember, I'm here to help if you're struggling with implementing anything.

**Comment by jeffcshelton** [comment]
Ok, as it turns out, we had effectively pre-planned for this feature and already added the `Trigger` struct definition along with the `FlightControlMessage::Trigger` variant a while back. These are the essential components you will be receiving as the flight computer to add these triggers.

Also, a slight change from before: let's attempt to do these trigger checks in Python before prematurely optimizing. Of course, try to make this Python integration as fast as possible (which I'll take a look at and may suggest improvements before merging, so don't worry too much about that). If we end up needing to do them in Rust, that's fine. Likely only a single function would change, and the vast majority of the feature's code would remain identical.

But having truly arbitrary abort checks rather than only predefined, rigid comparison operations seems to outweigh the _potential_ loss of performance on the order of 0.5 ms. I can already hear the propulsion team asking, "can we check both this PT and that PT, and only abort if they're both above a certain value?" Something even this simple would not be possible with Rust checks without implementing some crazy unnecessary stuff. So let's try it.

**Comment by shreeya-garg** [comment]
So to clarify, what I should do is create a new thread in the init_ function that will basically concurrently check_triggers at all times in the background. The information about what conditions lead to triggering will be sent in as a message in the WaitForOperator state. Once such a message is received, I need to write code so that it sends that condition to the triggers.py file. At any point, if the triggers.py file comes across a true condition, it should send an abort sequence back to the state/run-sequence thread? Is that correct?

**Comment by shreeya-garg** [comment]
Also, is the Trigger struct defined somewhere? I assume that the match statement essentially receives an instance of the Trigger struct, which stores as a variable a function that checks to see if an abort condition is met. I would need to then just extract this function and write if / then statements in the trigger.py file? In this file, is my main goal to establish connections with the respective valves? Like if the Trigger that it receives from the opperant, is something like if valve A exceeds x, abort, do I have to write code that connects to A, and compares to x? I guess I'm just a little bit confused about what each of my functions should be doing? Precisely what information do I get when a  Trigger message is received, and how do I handle that information?

**Comment by jeffcshelton** [comment]
To answer your first comment:
1. Yes, you should create a new thread in `init` which does this.
2. Yes, the conditions will be sent under `WaitForOperator`, if you receive the `Trigger` variant of `FlightControlMessage`.
3. Note that you will need a `Mutex` here (and probably more specifically an `Arc<Mutex<Vec<Trigger>>>` or `Arc<Mutex<HashMap<String, Trigger>>>`) which holds these triggers and can be accessed across threads.
4. `triggers.py` is not a separate file, and no file should be created. Each trigger is run as a single line of Python code directly by the embedded interpreter. Start by wrapping these checks in `Python::with_gil(|py| { ... })` and then probing the returned truth values after they run.
5. No, it won't necessarily be an abort sequence. The sequence run is specified by the `script` member of the `Trigger` struct. Just run that sequence in the same way that it's done in the `RunSequence` state, although by spawning a thread to call `common::sequences::run(&script)`. If that sequence happens to be `abort()`, then it is calling the abort sequence, but you don't have to worry about that.

To answer your second question:
1. Yes, it's defined in the `common` library, which you will need to clone and inspect separately (although VSCode will take you to the source if you right-click and select "Jump to Definition").
2. Again, no `trigger.py` file. I'm not sure exactly what you mean by "stores as a variable a function that checks...", and I also don't know what you mean by "establish connections to respective valves". The trigger-checking function should just run literally exactly what the script is; no modifications or additions.
3. The information that you get when the message is received is the members of the `Trigger` struct: `name`, `condition`, and `script`, all of which are `String`s. Hopefully the above comments explain how to handle them appropriately.

**Comment by shreeya-garg** [comment]
Thanks! I think the script stuff makes a little bit more sense now. In the initial issue, you mentioned that I should "make a new file for triggers, triggers.rs". I assume that requirement has changed now, and I should run the wrapped python scripts in the state file itself?

**Comment by jeffcshelton** [comment]
Right, make a file `trigger.rs` for your **Rust** code to handle triggers, `triggers.py` for Python code. Sorry about the confusion.

**Comment by shreeya-garg** [comment]
Sorry, one more question. Are the triggers being checked for and handled in python or rust?

**Comment by jeffcshelton** [comment]
The actual conditions are written in Python, but they are being directly executed in the interpreter embedded in Rust. So all of your code will be written in Rust. I would read up on [PyO3](https://pyo3.rs/v0.20.3/) a bit before attempting this issue. Also look at how it's used throughout the rest of the program.
